name: Deploy to Elastic Beanstalk
on:
  push:
    branches: [ main ]  # Only deploy from main branch
  workflow_run:
    workflows: ["Python CI"]
    types:
      - completed
    branches: [ main ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only deploy if tests pass
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Generate deployment package
      run: |
        zip -r deploy.zip . -x "*.git*" "venv/*" "myenv/*"
    
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: herbly-teaminder
        environment_name: herbly-teaminder-env
        region: us-east-1
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip