name: Deploy to Elastic Beanstalk
on:
  push:
    branches: [ main ]  # Only deploy from main branch
  workflow_run:
    workflows: ["Python CI"]
    types:
      - completed
    branches: [ main ]

# Add permissions for OIDC
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only deploy if tests pass
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  # IAM role ARN for OIDC
        aws-region: us-east-1
    
    - name: Generate deployment package
      run: |
        zip -r deploy.zip . -x "*.git*" "venv/*" "myenv/*"
    
    - name: Upload to S3
      env:
        APPLICATION_NAME: herbly-teaminder
        REGION: us-east-1
      run: |
        # Create S3 bucket if it doesn't exist
        aws s3api create-bucket \
          --bucket ${APPLICATION_NAME}-deploy \
          --region ${REGION} || true
        
        # Upload deployment package
        aws s3 cp deploy.zip s3://${APPLICATION_NAME}-deploy/

    - name: Deploy to EB
      env:
        APPLICATION_NAME: herbly-teaminder
        ENVIRONMENT_NAME: herbly-teaminder-env
        REGION: us-east-1
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name $APPLICATION_NAME \
          --version-label ${{ github.sha }} \
          --source-bundle S3Bucket=${APPLICATION_NAME}-deploy,S3Key=deploy.zip
        
        aws elasticbeanstalk update-environment \
          --application-name $APPLICATION_NAME \
          --environment-name $ENVIRONMENT_NAME \
          --version-label ${{ github.sha }}